version: "3.8"

services:

  accounts:
    image: ngx/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ngx-network
      
  loans:
    image: ngx/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ngx-network
  
  cards:
    image: ngx/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - ngx-network
      
networks:
  ngx-network:
  